data:extend({
    -- STARTUP SETTINGS
    {
        type = "bool-setting",
        name = "broom-atomic-bomb",
        setting_type = "startup",
        default_value = false,
        order = 'a',
    },
    -- MAP SETTINGS
    {
        type = "bool-setting",
        name = "broom-trees",
        setting_type = "runtime-global",
        default_value = false,
        order = 'a',
    },
    {
        type = "bool-setting",
        name = "broom-rock",
        setting_type = "runtime-global",
        default_value = false,
        order = 'b',
    },
    {
        type = "bool-setting",
        name = "broom-cliffs",
        setting_type = "runtime-global",
        default_value = false,
        order = 'c',
    },
    {
        type = "bool-setting",
        name = "broom-resources",
        setting_type = "runtime-global",
        default_value = false,
        order = 'd',
    },
    {
        type = "bool-setting",
        name = "broom-nuclear",
        setting_type = "runtime-global",
        default_value = false,
        order = 'e',
    },
    {
        type = "bool-setting",
        name = "broom-biter-creep",
        setting_type = "runtime-global",
        default_value = false,
        order = 'f',
    },
    {
        type = "bool-setting",
        name = "broom-decoratives",
        setting_type = "runtime-global",
        default_value = false,
        order = 'g',
    },
    {
        type = "bool-setting",
        name = "broom-decoratives-only-artificial-tiles",
        setting_type = "runtime-global",
        default_value = false,
        order = 'h',
    },
    {
        type = "bool-setting",
        name = "broom-corpses",
        setting_type = "runtime-global",
        default_value = false,
        order = 'i',
    },
    {
        type = "bool-setting",
        name = "broom-corpses-exclude-biter",
        setting_type = "runtime-global",
        default_value = false,
        order = 'j',
    },
    {
        type = "bool-setting",
        name = "broom-corpses-exclude-scorchmark",
        setting_type = "runtime-global",
        default_value = false,
        order = 'k',
    },
    {
        type = "bool-setting",
        name = "broom-corpses-exclude-stump",
        setting_type = "runtime-global",
        default_value = false,
        order = 'l',
    },
    {
        type = "bool-setting",
        name = "broom-corpses-exclude-remnants",
        setting_type = "runtime-global",
        default_value = false,
        order = 'm',
    },
})
